### ISSUE TITLE
Create Blog1 for Git tutorial.

### ISSUE THREAD

**Issue by kernelpanic77** [zense/JuniorsGitTutorial#2]
Create the first Blog, which would contain the instructions for the juniors. 
Along with a markdown template for the blog. 
The blog should contain:
-   which would contain the instructions for the juniors. 
-  Along with a markdown template for the blog. (Should be very specific about markdown format)
-  Add Suitable examples for them to add a youtube video using markdown. 
-  instructions to add author avatar and blog image.

**Comment by vijay-jaisankar** [comment]
Ya Assign me

**Comment by vijay-jaisankar** [comment]
@MegaMind77-coder Check this out
https://github.com/zense/JuniorsGitTutorial/commit/c8c71b9b24a8bd886f60c7a9de9dd1108bf92fbd
