### ISSUE TITLE
Remove Triangle from 2nd page animation

### ISSUE THREAD

**Issue by GaganAgarwal77** [zense/JuniorsGitTutorial#4]
So this is how the animation takes place, it hides all cards other than selected one, then takes a piece of the selected photo and adds it to the middle of the background image on the 2nd page, On closing this page, it takes that triangle and places it where the photo was on the first page. This triangle makes photos of people look weird, so removing this triangle part of the animation will make it look more clean.

**Comment by kernelpanic77** [comment]
@GaganAgarwal77 are you working on it ?

**Comment by GSri30** [comment]
Yea I removed that part. Close this.

**Comment by kernelpanic77** [comment]
Cool @GSri30
